import { Card } from "./ui";

export function SeriesBarChart({ title, subtitle, data, valueFormat = (v) => v, accent = "bg-blue-500/70", height = 140 }) {
  const values = (data || []).map((d) => Number(d.value || 0)); const max = Math.max(1, ...values);
  return <Card className="p-5"><div className="flex items-start justify-between gap-3 mb-5"><div><p className="section-kicker">Trend</p><h2 className="font-semibold text-white mt-1">{title}</h2>{subtitle && <p className="text-xs text-slate-500 mt-1">{subtitle}</p>}</div><span className="w-2 h-2 rounded-full bg-violet-300 mt-1.5" /></div>{values.length === 0 ? <p className="text-sm text-slate-500 py-8 text-center">No data in this period</p> : <div className="flex items-end gap-1.5" style={{ height }} role="img" aria-label={title}>{data.map((d, i) => { const v = Number(d.value || 0); const h = Math.max(4, Math.round((v / max) * (height - 28))); return <div key={`${d.label}-${i}`} className="flex-1 min-w-0 flex flex-col items-center justify-end h-full group relative"><span className="hidden group-hover:block absolute -top-1 translate-y-[-100%] text-[10px] text-white bg-slate-800 border border-slate-700 rounded-lg px-2 py-1 z-10 whitespace-nowrap shadow-lg">{d.label}: {valueFormat(v)}</span><div className={`w-full max-w-9 rounded-t-md ${accent} transition-all duration-300 group-hover:opacity-80`} style={{ height: h }} /><span className="text-[9px] text-slate-600 mt-2 truncate w-full text-center">{d.label}</span></div>; })}</div>}</Card>;
}
export function HBarList({ title, subtitle, items, valueFormat = (v) => v }) {
  const max = Math.max(1, ...(items || []).map((it) => Number(it.value || 0)));
  return <Card className="p-5"><div className="mb-5"><p className="section-kicker">Ranking</p><h2 className="font-semibold text-white mt-1">{title}</h2>{subtitle && <p className="text-xs text-slate-500 mt-1">{subtitle}</p>}</div>{(!items || items.length === 0) ? <p className="text-sm text-slate-500 py-8 text-center">No data yet</p> : <div className="space-y-4">{items.map((it, i) => { const v = Number(it.value || 0); const pct = Math.max(3, Math.round((v / max) * 100)); return <div key={it.label || i}><div className="flex items-center justify-between gap-3 text-sm mb-2"><span className="text-slate-300 truncate">{it.label}</span><span className="text-xs text-slate-500 shrink-0">{valueFormat(v)}</span></div><div className="h-2 rounded-full bg-slate-800 overflow-hidden"><div className="h-full rounded-full bg-gradient-to-r from-violet-600 to-cyan-400 transition-all duration-500" style={{ width: `${pct}%` }} /></div></div>; })}</div>}</Card>;
}
