import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, CalendarCheck, MessageSquare, ShieldCheck, Store, Users, Wallet, Wrench } from "lucide-react";
import api from "../services/api";
import { apiErrorMessage } from "../utils/errors";
import { Alert, Card, Spinner, StatCard } from "../components/ui";

export default function AdminDashboard() {
  const [stats, setStats] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { const load = async () => { setLoading(true); try { const { data } = await api.get("/admin/dashboard"); setStats(data); } catch (err) { setError(apiErrorMessage(err, "Failed to load platform statistics")); } finally { setLoading(false); } }; load(); }, []);
  if (loading) return <Spinner label="Loading platform statistics..." />;
  return <div><div className="flex flex-wrap items-end justify-between gap-4 mb-8 page-enter"><div><p className="section-kicker">Admin workspace</p><h1 className="page-title mt-2">Platform overview</h1><p className="page-subtitle">A calm view of everything happening across STORE.</p></div><span className="inline-flex items-center gap-2 text-xs text-emerald-300 bg-emerald-500/10 border border-emerald-400/20 rounded-full px-3 py-2"><span className="w-1.5 h-1.5 bg-emerald-300 rounded-full" /> All systems operational</span></div>{error && <Alert className="mb-5">{error}</Alert>}{stats && <><div className="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-3.5 mb-8 stagger-grid"><StatCard label="Users" value={stats.totalUsers} icon={Users} accent="text-blue-300" sub={`${stats.totalOwners} owners`} /><StatCard label="Stores" value={stats.totalStores} icon={Store} accent="text-violet-300" sub={`${stats.activeStores} active · ${stats.suspendedStores} suspended`} /><StatCard label="Services" value={stats.totalServices} icon={Wrench} accent="text-emerald-300" /><StatCard label="Bookings" value={stats.totalBookings} icon={CalendarCheck} accent="text-amber-300" sub={`${stats.pendingBookings} pending · ${stats.completedBookings} completed`} /><StatCard label="Ratings & reviews" value={stats.totalRatings} icon={MessageSquare} accent="text-rose-300" /></div><div className="grid lg:grid-cols-[1.15fr_.85fr] gap-5"><Card className="p-6"><div className="flex items-start justify-between gap-4 mb-6"><div><p className="section-kicker">Control center</p><h2 className="text-xl font-semibold text-white mt-1">Keep the marketplace healthy</h2><p className="text-sm text-slate-500 mt-2 max-w-md">Jump into the areas that need your attention or review the latest platform activity.</p></div><ShieldCheck size={22} className="text-emerald-300" /></div><div className="grid sm:grid-cols-3 gap-3"><ActionLink to="/admin/users" icon={Users} title="Manage users" text="Accounts & roles" /><ActionLink to="/admin/stores" icon={Store} title="Moderate stores" text="Status & quality" /><ActionLink to="/admin/stores/new" icon={Wallet} title="Add a store" text="Grow the network" /></div></Card><Card className="p-6"><p className="section-kicker">At a glance</p><h2 className="text-xl font-semibold text-white mt-1 mb-5">Platform mix</h2><div className="space-y-5"><MixRow label="Active stores" value={stats.totalStores ? Math.round((stats.activeStores / stats.totalStores) * 100) : 0} color="bg-emerald-400" /><MixRow label="Completed bookings" value={stats.totalBookings ? Math.round((stats.completedBookings / stats.totalBookings) * 100) : 0} color="bg-violet-400" /><MixRow label="Owner accounts" value={stats.totalUsers ? Math.round((stats.totalOwners / stats.totalUsers) * 100) : 0} color="bg-cyan-400" /></div></Card></div></>}</div>;
}
function ActionLink({ to, icon: Icon, title, text }) { return <Link to={to} className="group p-4 rounded-xl bg-slate-800/45 border border-slate-700/70 hover:border-violet-400/40 hover:bg-violet-500/[.06] transition"><Icon size={18} className="text-violet-300 mb-4" /><p className="text-sm font-semibold text-white group-hover:text-violet-200">{title}</p><p className="text-xs text-slate-500 mt-1">{text}</p><ArrowRight size={14} className="text-slate-600 mt-4 group-hover:text-violet-300 transition" /></Link>; }
function MixRow({ label, value, color }) { return <div><div className="flex items-center justify-between text-xs mb-2"><span className="text-slate-400">{label}</span><span className="text-slate-200 font-semibold">{value}%</span></div><div className="h-2 rounded-full bg-slate-800 overflow-hidden"><div className={`h-full ${color} rounded-full transition-all`} style={{ width: `${value}%` }} /></div></div>; }
