import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, CalendarCheck2, CalendarClock, Heart, MapPin, Search, Star, Timer, Wrench } from "lucide-react";
import api from "../services/api";
import { apiErrorMessage } from "../utils/errors";
import { formatDate, formatPrice } from "../utils/format";
import { Alert, Card, EmptyState, Spinner, StatCard, StatusBadge, Stars } from "../components/ui";

export default function CustomerDashboard() {
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { let active = true; (async () => { try { const res = await api.get("/customer/dashboard"); if (active) setData(res.data); } catch (err) { if (active) setError(apiErrorMessage(err, "Failed to load your dashboard")); } finally { if (active) setLoading(false); } })(); return () => { active = false; }; }, []);
  if (loading) return <Spinner label="Loading your dashboard..." />;
  if (error) return <Alert>{error}</Alert>;
  if (!data) return null;
  const { stats, upcoming = [], favoriteStores = [], recommendedStores = [], recentReviews = [] } = data;
  const statCards = [["Upcoming", stats.upcomingBookings, CalendarClock, "text-blue-300"], ["Pending", stats.pendingBookings, Timer, "text-amber-300"], ["Completed", stats.completedBookings, CalendarCheck2, "text-emerald-300"], ["Cancelled", stats.cancelledBookings, CalendarClock, "text-slate-300"], ["Favorites", stats.favorites, Heart, "text-rose-300"], ["Avg rating given", stats.averageRatingGiven ?? "—", Star, "text-amber-300", `${stats.totalReviews} reviews`]];
  return <div>
    <div className="flex flex-wrap items-end justify-between gap-4 mb-8 page-enter"><div><p className="section-kicker">Your space</p><h1 className="page-title mt-2">Good to see you.</h1><p className="page-subtitle">Your bookings, favorites and activity at a glance.</p></div><Link to="/stores"><span className="inline-flex items-center gap-2 text-sm font-semibold text-white bg-blue-600 hover:bg-blue-500 rounded-[10px] px-4 py-2.5 transition hover:-translate-y-px"><Search size={16} /> Discover stores <ArrowRight size={15} /></span></Link></div>
    <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-3.5 mb-8 stagger-grid">{statCards.map(([label, value, icon, accent, sub]) => <StatCard key={label} label={label} value={value} icon={icon} accent={accent} sub={sub} />)}</div>
    <div className="grid xl:grid-cols-[1.15fr_.85fr] gap-5 mb-5">
      <Card className="overflow-hidden"><div className="flex items-center justify-between px-5 py-4 border-b border-slate-800"><div><p className="section-kicker">Next up</p><h2 className="font-semibold text-white mt-1">Upcoming bookings</h2></div><Link to="/my-bookings" className="text-xs text-blue-300 hover:text-white font-semibold transition">View all <ArrowRight size={13} className="inline ml-1" /></Link></div>{upcoming.length === 0 ? <EmptyState title="Your calendar is clear" icon={CalendarClock}><Link to="/stores" className="text-blue-300 hover:text-white">Find a service to book →</Link></EmptyState> : <ul className="divide-y divide-slate-800">{upcoming.map((b) => <li key={b.id}><Link to={`/bookings/${b.id}`} className="flex items-center justify-between gap-3 px-5 py-4 hover:bg-slate-800/40 transition group"><div className="min-w-0 flex items-center gap-3"><span className="w-9 h-9 rounded-xl bg-blue-500/10 border border-blue-400/15 grid place-items-center shrink-0"><CalendarClock size={16} className="text-blue-300" /></span><div className="min-w-0"><p className="text-sm text-white truncate group-hover:text-blue-200 transition">{b.storeName}</p><p className="text-xs text-slate-500 mt-0.5 truncate">{b.serviceName}</p></div></div><div className="flex items-center gap-3 shrink-0"><div className="text-right hidden sm:block"><p className="text-xs text-slate-300">{formatDate(b.bookingDate)} · {b.startTime?.slice(0, 5)}</p><p className="text-xs text-slate-500 mt-0.5">{formatPrice(b.price)}</p></div><StatusBadge status={b.status} /><ArrowRight size={15} className="text-slate-600 group-hover:text-blue-300 transition" /></div></Link></li>)}</ul>}</Card>
      <Card className="overflow-hidden"><div className="flex items-center justify-between px-5 py-4 border-b border-slate-800"><div><p className="section-kicker">Saved places</p><h2 className="font-semibold text-white mt-1">Favorite stores</h2></div><Link to="/favorites" className="text-xs text-blue-300 hover:text-white font-semibold transition">View all <ArrowRight size={13} className="inline ml-1" /></Link></div>{favoriteStores.length === 0 ? <EmptyState title="No favorites yet" icon={Heart}><Link to="/stores" className="text-blue-300 hover:text-white">Explore stores →</Link></EmptyState> : <ul className="divide-y divide-slate-800">{favoriteStores.map((s) => <li key={s.id}><Link to={`/stores/${s.id}`} className="flex items-center justify-between gap-3 px-5 py-4 hover:bg-slate-800/40 transition group"><div className="min-w-0"><p className="text-sm text-white truncate group-hover:text-blue-200">{s.name}</p><p className="text-xs text-slate-500 mt-1 truncate">{s.category || "Store"}</p></div><Heart size={15} className="text-rose-300 fill-rose-300 shrink-0" /></Link></li>)}</ul>}</Card>
    </div>
    <div className="grid xl:grid-cols-2 gap-5"><Card className="overflow-hidden"><div className="flex items-center justify-between px-5 py-4 border-b border-slate-800"><div><p className="section-kicker">For you</p><h2 className="font-semibold text-white mt-1">Recommended stores</h2></div><Link to="/stores" className="text-xs text-blue-300 hover:text-white font-semibold transition">Browse <ArrowRight size={13} className="inline ml-1" /></Link></div>{recommendedStores.length === 0 ? <EmptyState title="Recommendations are coming" icon={Wrench}>Browse stores to find a great local service.</EmptyState> : <ul className="divide-y divide-slate-800">{recommendedStores.map((s) => <li key={s.id}><Link to={`/stores/${s.id}`} className="flex items-center justify-between gap-3 px-5 py-4 hover:bg-slate-800/40 transition group"><div className="min-w-0"><p className="text-sm text-white truncate group-hover:text-blue-200">{s.name}</p><p className="text-xs text-slate-500 mt-1 flex items-center gap-1 truncate"><MapPin size={12} /> {s.category || "Store"} · {s.address}</p></div><span className="text-xs text-blue-300 shrink-0 group-hover:text-white">Explore <ArrowRight size={13} className="inline ml-1" /></span></Link></li>)}</ul>}</Card><Card className="overflow-hidden"><div className="flex items-center justify-between px-5 py-4 border-b border-slate-800"><div><p className="section-kicker">Your voice</p><h2 className="font-semibold text-white mt-1">Recent reviews</h2></div><Link to="/profile" className="text-xs text-blue-300 hover:text-white font-semibold transition">My reviews <ArrowRight size={13} className="inline ml-1" /></Link></div>{recentReviews.length === 0 ? <EmptyState title="No reviews yet" icon={Star}>Rate a store after a completed visit — it appears here.</EmptyState> : <ul className="divide-y divide-slate-800">{recentReviews.map((r) => <li key={r.id} className="px-5 py-4"><div className="flex items-center justify-between gap-3"><p className="text-sm font-medium text-white">{r.store?.name || "Store"}</p><Stars value={r.rating} size={12} /></div>{r.comment && <p className="text-sm text-slate-400 mt-2 leading-relaxed">{r.comment}</p>}</li>)}</ul>}</Card></div>
  </div>;
}
