import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, CalendarPlus, CheckCircle2, Clock, Heart, Mail, MapPin, MessageSquare, Phone, Store as StoreIcon } from "lucide-react";
import api from "../services/api";
import { apiErrorMessage } from "../utils/errors";
import { formatDateTime, formatPrice } from "../utils/format";
import { getRole } from "../utils/auth";
import RatingModal from "../components/RatingModal";
import BookingModal from "../components/BookingModal";
import { Alert, Button, Card, EmptyState, Spinner, Stars } from "../components/ui";

const DAY_NAMES = { 1: "Mon", 2: "Tue", 3: "Wed", 4: "Thu", 5: "Fri", 6: "Sat", 7: "Sun" };
const VISUALS = { SALON: "from-fuchsia-900 via-violet-900 to-slate-950", REPAIR: "from-orange-900 via-amber-900/60 to-slate-950", FITNESS: "from-cyan-900 via-blue-900/60 to-slate-950", PHOTOGRAPHY: "from-indigo-900 via-fuchsia-900/50 to-slate-950", CLEANING: "from-emerald-900 via-teal-900/50 to-slate-950" };

export default function StoreDetail() {
  const { id } = useParams(); const navigate = useNavigate(); const isCustomer = getRole() === "USER";
  const [store, setStore] = useState(null); const [services, setServices] = useState([]); const [ratings, setRatings] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [bookingService, setBookingService] = useState(null); const [rateOpen, setRateOpen] = useState(false); const [favBusy, setFavBusy] = useState(false);
  useEffect(() => { let active = true; (async () => { try { const [storeRes, servicesRes, ratingsRes] = await Promise.all([api.get(`/stores/${id}`), api.get(`/services/store/${id}`), api.get(`/ratings/store/${id}`)]); if (!active) return; setStore(storeRes.data.store); setServices(servicesRes.data.services || []); setRatings(ratingsRes.data); setError(""); } catch (err) { if (active) setError(apiErrorMessage(err, "Failed to load this store")); } finally { if (active) setLoading(false); } })(); return () => { active = false; }; }, [id]);
  const toggleFavorite = async () => { setFavBusy(true); try { if (store.isFavorite) { await api.delete(`/favorites/${store.id}`); setNotice("Removed from favorites"); } else { await api.post("/favorites", { storeId: store.id }); setNotice("Added to favorites"); } setStore((s) => ({ ...s, isFavorite: !s.isFavorite })); } catch (err) { setError(apiErrorMessage(err, "Could not update favorite")); } finally { setFavBusy(false); } };
  const reload = async () => { try { const [storeRes, ratingsRes] = await Promise.all([api.get(`/stores/${id}`), api.get(`/ratings/store/${id}`)]); setStore(storeRes.data.store); setRatings(ratingsRes.data); } catch { /* modal has already handled the mutation */ } };
  if (loading) return <Spinner label="Loading store..." />;
  if (error || !store) return <Card><EmptyState icon={StoreIcon} title="Store unavailable"><p className="mb-4">{error || "Store not found"}</p><Button variant="ghost" onClick={() => navigate(-1)}><ArrowLeft size={15} /> Go back</Button></EmptyState></Card>;
  const distribution = ratings?.distribution || { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 }; const maxDist = Math.max(1, ...Object.values(distribution)); const category = store.category?.replace(/_/g, " "); const source = store.imageUrl || store.image;
  return <div>
    <button onClick={() => navigate(-1)} className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white mb-5 transition"><ArrowLeft size={15} /> Back to stores</button>{notice && <Alert kind="success" className="mb-4">{notice}</Alert>}
    <section className={`relative overflow-hidden rounded-2xl border border-slate-700/80 bg-gradient-to-br ${VISUALS[category] || "from-violet-900 via-indigo-900/60 to-slate-950"} min-h-[260px] mb-6`}><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_20%,rgba(255,255,255,.18),transparent_25%),linear-gradient(0deg,rgba(8,11,18,.93),rgba(8,11,18,.15))]" />{source && <img src={source} alt="" className="absolute inset-0 w-full h-full object-cover opacity-35 mix-blend-screen" />}<StoreIcon size={190} strokeWidth={.6} className="absolute right-8 top-7 text-white/[.08]" /><div className="relative z-10 flex flex-col justify-end min-h-[260px] p-6 sm:p-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><div className="flex flex-wrap items-center gap-2 mb-3"><span className="inline-flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-[.14em] text-white/75 bg-white/10 border border-white/15 rounded-full px-2.5 py-1"><CheckCircle2 size={12} className="text-emerald-300" /> {store.status || "Active"}</span>{category && <span className="text-[10px] font-bold uppercase tracking-[.14em] text-violet-100/75">{category}</span>}</div><h1 className="text-3xl sm:text-4xl font-bold tracking-[-.05em] text-white">{store.name}</h1><div className="flex items-center gap-2 mt-3"><Stars value={store.averageRating} size={16} /><span className="text-sm text-slate-300">{Number(store.averageRating) > 0 ? store.averageRating : "New"}</span><span className="text-slate-500 text-sm">· {store.totalServices || services.length} services</span></div></div>{isCustomer && <div className="flex items-center gap-2"><Button variant={store.isFavorite ? "primary" : "outline"} onClick={toggleFavorite} loading={favBusy}><Heart size={15} className={store.isFavorite ? "fill-current" : ""} />{store.isFavorite ? "Saved" : "Save"}</Button><Button variant="secondary" onClick={() => setRateOpen(true)}><MessageSquare size={15} /> Review</Button></div>}</div></div></section>
    <div className="grid lg:grid-cols-[1.15fr_.85fr] gap-5"><div className="space-y-5"><Card className="p-5 sm:p-6"><div className="flex flex-wrap gap-x-6 gap-y-3 text-sm text-slate-400">{store.address && <span className="flex items-center gap-2"><MapPin size={15} className="text-violet-300" /> {store.address}</span>}{store.phone && <span className="flex items-center gap-2"><Phone size={15} className="text-slate-500" /> {store.phone}</span>}{store.email && <span className="flex items-center gap-2"><Mail size={15} className="text-slate-500" /> {store.email}</span>}<span className="flex items-center gap-2"><Clock size={15} className="text-slate-500" />{store.hasCustomHours ? "Custom operating hours" : `${store.openingTime?.slice(0, 5) || "—"} – ${store.closingTime?.slice(0, 5) || "—"}`}</span></div>{store.description && <p className="text-sm text-slate-300 leading-relaxed mt-5 pt-5 border-t border-slate-800">{store.description}</p>}{store.hasCustomHours && store.operatingHours?.length > 0 && <div className="mt-5 pt-5 border-t border-slate-800 grid grid-cols-2 sm:grid-cols-4 gap-2">{[...store.operatingHours].sort((a, b) => a.dayOfWeek - b.dayOfWeek).map((h) => <div key={h.dayOfWeek} className="bg-slate-800/50 rounded-xl px-3 py-2.5"><p className="font-semibold text-slate-300 text-xs">{DAY_NAMES[h.dayOfWeek]}</p><p className={`text-xs mt-1 ${h.closed ? "text-red-400" : "text-slate-500"}`}>{h.closed ? "Closed" : `${h.openTime?.slice(0, 5)} – ${h.closeTime?.slice(0, 5)}`}</p></div>)}</div>}</Card><div><div className="flex items-end justify-between gap-3 mb-3"><div><p className="section-kicker">What we offer</p><h2 className="text-xl font-semibold text-white mt-1">Services & prices</h2></div><span className="text-xs text-slate-500">{services.length} available</span></div>{services.length === 0 ? <Card><EmptyState icon={StoreIcon} title="No services available">This store has not added any services yet.</EmptyState></Card> : <div className="space-y-3">{services.map((service) => <Card key={service.id} className="p-5 flex flex-wrap items-center justify-between gap-4 card-hover"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h3 className="font-semibold text-white">{service.name}</h3><button onClick={() => navigate(`/services/${service.id}`)} className="text-[11px] text-blue-300 hover:text-white font-semibold transition">Details</button></div>{service.description && <p className="text-sm text-slate-400 mt-1.5 line-clamp-2 leading-relaxed">{service.description}</p>}<p className="text-xs text-slate-500 mt-3 flex items-center gap-1.5"><Clock size={12} /> {service.estimatedMinutes} min</p></div><div className="flex items-center gap-4"><p className="text-xl font-bold text-white">{formatPrice(service.price)}</p>{isCustomer ? <Button size="sm" onClick={() => setBookingService(service)}><CalendarPlus size={14} /> Book now</Button> : <span className="text-xs text-slate-600">Customer booking</span>}</div></Card>)}</div>}</div></div>
      <Card className="p-5 sm:p-6 h-fit lg:sticky lg:top-[92px]"><div className="flex items-start justify-between gap-3 mb-5"><div><p className="section-kicker">Social proof</p><h2 className="font-semibold text-white mt-1">Ratings & reviews</h2></div><span className="text-3xl font-bold text-white">{Number(ratings?.averageRating || 0) > 0 ? ratings.averageRating : "—"}</span></div><div className="flex items-center gap-2 pb-5 border-b border-slate-800"><Stars value={ratings?.averageRating} size={14} /><span className="text-xs text-slate-500">{ratings?.totalRatings || 0} review{ratings?.totalRatings === 1 ? "" : "s"}</span></div><div className="space-y-2.5 py-5 border-b border-slate-800">{[5, 4, 3, 2, 1].map((star) => { const count = distribution[star] || 0; const pct = ratings?.totalRatings ? Math.round((count / ratings.totalRatings) * 100) : 0; return <div key={star} className="flex items-center gap-2 text-xs text-slate-500"><span className="w-7 shrink-0">{star} <span className="text-amber-400">★</span></span><div className="flex-1 h-1.5 rounded-full bg-slate-800 overflow-hidden"><div className="h-full bg-amber-400 rounded-full transition-all" style={{ width: `${(count / maxDist) * 100}%` }} /></div><span className="w-9 text-right shrink-0">{pct}%</span></div>; })}</div><div className="space-y-4 max-h-[430px] overflow-y-auto pr-1 pt-5">{ratings?.ratings?.length === 0 && <p className="text-sm text-slate-500">No reviews yet. Be the first!</p>}{ratings?.ratings?.map((r) => <div key={r.id} className="border-b border-slate-800 last:border-0 pb-4 last:pb-0"><div className="flex items-center justify-between gap-3 mb-1.5"><p className="text-sm font-medium text-slate-200">{r.userName}</p><span className="text-[10px] text-slate-600">{formatDateTime(r.createdAt)}</span></div><Stars value={r.rating} size={12} />{r.comment && <p className="text-sm text-slate-400 mt-2 leading-relaxed">{r.comment}</p>}{r.ownerReply && <div className="ml-3 mt-3 border-l-2 border-blue-500/40 pl-3"><p className="text-[11px] text-slate-500">Store reply</p><p className="text-sm text-slate-300 mt-0.5">{r.ownerReply}</p></div>}</div>)}</div></Card></div>
    <BookingModal open={Boolean(bookingService)} store={store} service={bookingService} onClose={() => setBookingService(null)} /><RatingModal open={rateOpen} storeId={store.id} storeName={store.name} onClose={() => setRateOpen(false)} onSubmitted={() => { setRateOpen(false); reload(); }} />
  </div>;
}
