import { useCallback, useEffect, useRef, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { ArrowRight, Clock, LocateFixed, MapPin, Search, Sparkles, Store, X } from "lucide-react";
import api from "../services/api";
import { apiErrorMessage } from "../utils/errors";
import { formatPrice } from "../utils/format";
import { Alert, Button, Card, EmptyState, Field, Input, Pagination, Select, Spinner, Stars } from "../components/ui";

const CATEGORIES = ["SALON", "REPAIR", "FITNESS", "PHOTOGRAPHY", "CLEANING", "AUTO CARE"];
const SORT_OPTIONS = [{ value: "highest_rated", label: "Highest rated" }, { value: "most_reviewed", label: "Most reviewed" }, { value: "nearest", label: "Nearest" }, { value: "price", label: "Price" }, { value: "newest", label: "Newest" }, { value: "name", label: "Name A–Z" }];
const VISUALS = { SALON: "from-fuchsia-900/80 via-violet-900/50 to-slate-900", REPAIR: "from-orange-900/70 via-amber-900/40 to-slate-900", FITNESS: "from-cyan-900/70 via-blue-900/45 to-slate-900", PHOTOGRAPHY: "from-indigo-900/80 via-fuchsia-900/40 to-slate-900", CLEANING: "from-emerald-900/70 via-teal-900/40 to-slate-900", "AUTO CARE": "from-slate-700 via-blue-900/50 to-slate-900" };

function StoreVisual({ store }) {
  const category = store.category?.replace(/_/g, " ");
  const source = store.imageUrl || store.image;
  return <div className={`relative h-40 overflow-hidden bg-gradient-to-br ${VISUALS[category] || "from-violet-900/70 via-slate-800 to-slate-950"}`}>
    {source ? <img src={source} alt="" className="w-full h-full object-cover opacity-80 group-hover:scale-105 transition duration-500" /> : <><div className="absolute inset-0 opacity-50 bg-[radial-gradient(circle_at_20%_20%,rgba(255,255,255,.25),transparent_30%),linear-gradient(135deg,transparent_45%,rgba(255,255,255,.06)_45%,transparent_60%)]" /><Store size={62} strokeWidth={1} className="absolute right-5 bottom-4 text-white/20 group-hover:scale-110 group-hover:text-white/30 transition duration-500" /></>}
    <div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 via-transparent to-transparent" />
    {category && <span className="absolute left-4 bottom-3 text-[10px] font-bold tracking-[.12em] uppercase text-white/80">{category}</span>}
  </div>;
}

export default function StoreList() {
  const [searchParams, setSearchParams] = useSearchParams();
  const page = Number(searchParams.get("page")) || 1; const search = searchParams.get("search") || ""; const category = searchParams.get("category") || ""; const service = searchParams.get("service") || ""; const minRating = searchParams.get("minRating") || ""; const maxPrice = searchParams.get("maxPrice") || ""; const openNow = searchParams.get("openNow") === "true"; const sort = searchParams.get("sort") || "highest_rated"; const order = searchParams.get("order") || "DESC"; const lat = Number(searchParams.get("lat")) || null; const lng = Number(searchParams.get("lng")) || null;
  const [data, setData] = useState([]); const [pagination, setPagination] = useState({ page: 1, totalPages: 1, total: 0 }); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [searchInput, setSearchInput] = useState(search); const [locating, setLocating] = useState(false); const [geoNotice, setGeoNotice] = useState(""); const locationRef = useRef(null);
  const updateParams = useCallback((patch) => { const next = new URLSearchParams(searchParams); Object.entries(patch).forEach(([key, value]) => { if (value === "" || value === undefined || value === null || value === false) next.delete(key); else next.set(key, String(value)); }); if (!("page" in patch)) next.delete("page"); setSearchParams(next); }, [searchParams, setSearchParams]);
  useEffect(() => { let active = true; (async () => { try { const params = { page, limit: 9 }; if (search) params.search = search; if (category) params.category = category; if (service) params.service = service; if (minRating) params.minRating = minRating; if (maxPrice) params.maxPrice = maxPrice; if (openNow) params.openNow = "true"; if (lat && lng) { params.lat = lat; params.lng = lng; } params.sort = sort; if (sort === "name" || sort === "price") params.order = order; const { data: res } = await api.get("/stores", { params }); if (!active) return; setData(res.data || []); setPagination(res.pagination || { page: 1, totalPages: 1, total: 0 }); setError(""); } catch (err) { if (active) setError(apiErrorMessage(err, "Failed to load stores")); } finally { if (active) setLoading(false); } })(); return () => { active = false; }; }, [page, search, category, service, minRating, maxPrice, openNow, sort, order, lat, lng]);
  const submitSearch = (e) => { e.preventDefault(); updateParams({ search: searchInput.trim() }); };
  const useMyLocation = () => { if (!navigator.geolocation) { setGeoNotice("Geolocation is not available in this browser — distance sorting needs your coordinates."); return; } setLocating(true); setGeoNotice(""); navigator.geolocation.getCurrentPosition((pos) => { setLocating(false); locationRef.current = { lat: pos.coords.latitude, lng: pos.coords.longitude }; updateParams({ lat: pos.coords.latitude.toFixed(5), lng: pos.coords.longitude.toFixed(5), sort: "nearest" }); }, () => { setLocating(false); setGeoNotice("We could not access your location — distance sorting needs your coordinates."); }, { enableHighAccuracy: false, timeout: 8000 }); };
  const hasFilters = search || category || service || minRating || maxPrice || openNow || (lat && lng);
  return <div>
    <div className="flex flex-wrap items-end justify-between gap-4 mb-7 page-enter"><div><p className="section-kicker">Explore</p><h1 className="page-title mt-2">Find your next place.</h1><p className="page-subtitle">Trusted local services, ready when you are.</p></div><div className="hidden sm:flex items-center gap-2 text-xs text-slate-500"><Sparkles size={14} className="text-amber-300" /> {pagination.total || 0} places to explore</div></div>
    <Card className="p-4 sm:p-5 mb-7"><form onSubmit={submitSearch} className="space-y-4"><div className="flex flex-col md:flex-row gap-3"><div className="flex-1 relative"><Search size={17} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-500" /><Input className="pl-10 h-11" placeholder="Search stores, services or areas..." value={searchInput} onChange={(e) => setSearchInput(e.target.value)} aria-label="Search stores" /></div><Button type="button" variant="outline" loading={locating} onClick={useMyLocation}><LocateFixed size={15} /> Use my location</Button><Button type="submit"><Search size={15} /> Search</Button></div><div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-3"><Field><Select value={category} onChange={(e) => updateParams({ category: e.target.value })} aria-label="Filter by category"><option value="">All categories</option>{CATEGORIES.map((c) => <option key={c} value={c}>{c.replace(/_/g, " ")}</option>)}</Select></Field><Field><Input placeholder="Service name..." value={service} onChange={(e) => updateParams({ service: e.target.value })} aria-label="Filter by service" /></Field><Field><Select value={minRating} onChange={(e) => updateParams({ minRating: e.target.value })} aria-label="Minimum rating"><option value="">Any rating</option><option value="4.5">4.5+</option><option value="4">4.0+</option><option value="3">3.0+</option></Select></Field><Field><Select value={maxPrice} onChange={(e) => updateParams({ maxPrice: e.target.value })} aria-label="Maximum price"><option value="">Any price</option><option value="500">Under ₹500</option><option value="1000">Under ₹1,000</option><option value="2000">Under ₹2,000</option><option value="5000">Under ₹5,000</option></Select></Field><Field><Select value={sort} onChange={(e) => updateParams({ sort: e.target.value, order: "DESC" })} aria-label="Sort stores">{SORT_OPTIONS.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</Select></Field>{(sort === "name" || sort === "price") && <Field><Select value={order} onChange={(e) => updateParams({ order: e.target.value })} aria-label="Sort direction"><option value="DESC">High → low</option><option value="ASC">Low → high</option></Select></Field>}</div><div className="flex flex-wrap items-center gap-4"><label className="inline-flex items-center gap-2 text-sm text-slate-400 cursor-pointer select-none"><input type="checkbox" checked={openNow} onChange={(e) => updateParams({ openNow: e.target.checked })} className="accent-violet-500" /> Open now</label>{hasFilters && <button type="button" onClick={() => { setSearchInput(""); setSearchParams({}); }} className="inline-flex items-center gap-1.5 text-xs text-slate-400 hover:text-white font-medium transition"><X size={13} /> Clear filters</button>}</div></form></Card>
    {geoNotice && <Alert className="mb-4">{geoNotice}</Alert>}{error && <Alert className="mb-4">{error}</Alert>}
    {loading ? <Spinner label="Finding great places..." /> : data.length === 0 ? <Card><EmptyState icon={Store} title="No stores found">Try a different search term or clear the filters.</EmptyState></Card> : <><div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-5 stagger-grid">{data.map((store) => <Link key={store.id} to={`/stores/${store.id}`} className="group premium-card card-hover overflow-hidden"><StoreVisual store={store} /><div className="p-5"><div className="flex items-center justify-between gap-3 mb-2"><h3 className="font-semibold text-white group-hover:text-violet-200 transition leading-snug truncate">{store.name}</h3>{store.distance != null && <span className="text-[10px] text-slate-400 shrink-0">{store.distance} km</span>}</div><div className="flex items-center gap-2 mb-3"><Stars value={store.averageRating} size={13} /><span className="text-xs text-slate-400">{Number(store.averageRating) > 0 ? store.averageRating : "New"} <span className="text-slate-600">({store.ratingCount})</span></span></div><p className="text-sm text-slate-400 line-clamp-2 mb-4 min-h-10 leading-relaxed">{store.description || "Explore services and book your next experience."}</p><div className="space-y-2 text-xs text-slate-500"><p className="flex items-center gap-1.5"><MapPin size={13} className="shrink-0 text-slate-600" /><span className="truncate">{store.address}</span></p><p className="flex items-center gap-1.5"><Clock size={13} className="shrink-0 text-slate-600" />{store.openingTime?.slice(0, 5)} – {store.closingTime?.slice(0, 5)} <span className="text-slate-700">·</span> {store.serviceCount} services</p>{store.minPrice != null && <p className="flex items-center justify-between pt-2 border-t border-slate-800 text-violet-300 font-semibold">From {formatPrice(store.minPrice)} <ArrowRight size={14} className="text-slate-500 group-hover:text-violet-300 transition" /></p>}</div></div></Link>)}</div><Pagination page={pagination.page} totalPages={pagination.totalPages} onChange={(next) => updateParams({ page: next })} /><p className="text-center text-xs text-slate-600 -mt-2">{pagination.total} store{pagination.total === 1 ? "" : "s"} found</p></>}
  </div>;
}
